---
- hosts: all
  become: True
  tasks:
    - name: Installing git docker and apache server Redhat
      yum:
        name: "{{item}}" 
        state: present
      with_items:
        - git
        - httpd
      when: ansible_os_family == "RedHat"
    - name: Installing git docker and apache server Ubuntu
      apt:
        name: "{{item}}" 
        state: present
      with_items:
        - git
        - apache2
      when: ansible_os_family == "Debian"  
    - name: Starting Apache Server on RedHat
      service:
        name: "{{item}}"
        state: started
      with_items:
        - httpd
      when: ansible_os_family == "RedHat"
    - name: Starting Apache Server on Ubuntu
      service:
        name: "{{item}}"
        state: started
      with_items:
        - apache2
      when: ansible_os_family == "Debian"
    - name: Coping index.html in Redhat
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
      when: ansible_os_family == "RedHat"
      notify:
        - Restarting Apache Server
    - name: Coping index.html ubuntu
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
      when: ansible_os_family == "Debian"
      notify:
        - Restarting Apache Server
  handlers:
    - name: Restarting Apache Server
      service: 
        name: "{{item}}"
        state: restarted
      with_items:
        - httpd
        - apache2
